services:
  shell:
    build: .
    entrypoint:
      - /bin/sh
    image: 368099029718.dkr.ecr.us-west-2.amazonaws.com/sync-security-groups
    init: true
    volumes:
      - ./:/home/python/sync-security-groups
