services:
  shell:
    entrypoint:
      - /bin/bash
    image: ghcr.io/informatica-na-presales-ops/sync-security-groups:latest
    init: true
    volumes:
      - ./:/home/python/sync-security-groups
