name: Build the release container image

on:
  release:
    types: [published]

jobs:

  build:
    name: Build the release container image
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v1
    - name: Get the release tag
      id: get-release-tag
      run: echo ::set-output name=release-tag::${GITHUB_REF/refs\/tags\//}
    - name: Build the container image
      run: docker build --file Dockerfile --tag docker.pkg.github.com/informatica-na-presales-ops/sync-security-groups/sync-security-groups:${{ steps.get-release-tag.outputs.release-tag }} .
    - name: Log in to the registry
      run: docker login --password ${DOCKER_PASSWORD} --username ${DOCKER_USERNAME} docker.pkg.github.com
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: Push the image to the registry
      run: docker image push docker.pkg.github.com/informatica-na-presales-ops/sync-security-groups/sync-security-groups:${{ steps.get-release-tag.outputs.release-tag }}
